//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChaProducts
    {
        public int ChaProdID { get; set; }
        public int ProductID { get; set; }
        public int ProdKolvo { get; set; }
        public int ChaTypeID { get; set; }
    
        public virtual ChaTypes ChaTypes { get; set; }
        public virtual Products Products { get; set; }

        public ChaProducts() { }
        public ChaProducts(int productID, int prodKolvo, int chaTypeID)
        {
            ProductID = productID;
            ProdKolvo = prodKolvo;
            ChaTypeID = chaTypeID;
        }
    }
}
