//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceStore
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RaceStoreDbEntities3 : DbContext
    {
        public RaceStoreDbEntities3()
            : base("name=RaceStoreDbEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Addres> Addres { get; set; }
        public virtual DbSet<ChaProducts> ChaProducts { get; set; }
        public virtual DbSet<ChaTypes> ChaTypes { get; set; }
        public virtual DbSet<Offices> Offices { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<Provides> Provides { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
        public virtual DbSet<TypeProducts> TypeProducts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
