//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Products()
        {
            this.ChaProducts = new HashSet<ChaProducts>();
        }
    
        public int ProductID { get; set; }
        public string ProductTitle { get; set; }
        public string Info { get; set; }
        public string Price { get; set; }
        public int Kolvo { get; set; }
        public int TypeProductID { get; set; }
        public int ProviderID { get; set; }
        public int StorageID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChaProducts> ChaProducts { get; set; }
        public virtual Provides Provides { get; set; }
        public virtual Storages Storages { get; set; }
        public virtual TypeProducts TypeProducts { get; set; }
    }
}
