//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaceStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int UserID { get; set; }
        public string Logg { get; set; }
        public string Pass { get; set; }
        public string Fname { get; set; }
        public string Iname { get; set; }
        public string Oname { get; set; }
        public int OfficeID { get; set; }
        public int RoleID { get; set; }
    
        public virtual Offices Offices { get; set; }
        public virtual Roles Roles { get; set; }

         public string FIO => Fname +" "+ Iname + " "+Oname;

        public Users() { }
        public Users(string logg, string pass, string fname, string iname, string oname, int officeID, int roleID)
        {
            Logg = logg;
            Pass = pass;
            Fname = fname;
            Iname = iname;
            Oname = oname;
            OfficeID = officeID;
            RoleID = roleID;
        }
    }
}
